### ISSUE TITLE
Setting the wifi AP and password

### ISSUE THREAD

**Issue by peter-clarke** [mrizvic/nodemcu-uart2mqtt#2]
Could you explain how you would set the wifi AP and password e.g. using Putty?
Whatever I try thows various errors.

**Comment by jumpswitch** [comment]
How did you try to enter AP and pass and what were the errors present at that time?

The procedure to setup WIFI AP and password is following:

```
- boot up esp8266/nodemcu
- connect with serial terminal to device
- enter your wifi ap name followed by \r or \n
- enter your wifi password followed by \r or \n
- wait a moment or inspect STATUS_REGISTER by sending 0xf0 over serial line
- anything you send over serial line will be published according to global variables in init.lua to your MQTT setup
```

Did you inspect init.lua source before uploading? If not please read installation procedure in README.md file. It was lacking some not so obvious stuff so I updated the installation procedure recently. It doesnt work in PuTTY for me as well. I was using this terminal while writing the code and testing functionalities https://sites.google.com/site/terminalbpp/ I encourage you to use it :) When I find more time I will debug and try to make it work with PuTTY because I use it a lot too.

**Comment by jumpswitch** [comment]
I got it working in putty. Instead of pressing RETURN every time you need to hit CTRL+J in order to send 0x0a character which is treated as line termination.

So for example if your SSID is `mynet` and password is `mypass` the procedure for PuTTY is following:

```
- boot up device
- connect with PuTTY
- type mynet and hit CTRL+J
- type mypass and hit CTRL+J
- wait a moment
- type test and hit CTRL+J
```

If you get `undefined error` after typing `test` and CTRL+J then you must wait another moment. It is because AP and MQTT connections havent been established yet. You can observe STATUS_REGISTER if you are using the terminal I suggested earlier.
Cheers :)

**Comment by jumpswitch** [comment]
You can also change value of `UART_TERMINATOR` variable in init.lua. Change value from `\n` to `\r`:

```
UART_TERMINATOR1='\r'
```

`\r` represents RETURN key in PuTTY with default settings.

**Comment by jumpswitch** [comment]
Below is working example I wrote for Arduino mega 2560. Attach esp8266 to tx1/rx1 pins.

```
int x=0;

void setup() {
  // initial delay
  delay(2000);

  // init of serial ports
  // Serial = USB - connected to your workstation
  // Serial1 = tx1/rx1 - connected to esp8266
  Serial.begin(9600);
  Serial1.begin(9600);

  // reset esp8266
  Serial.println("0xf3");
  Serial1.write(0xf3);
  Serial.println("0x0a");
  Serial1.write(0x0a);
  delay(4000);

  // send SSID to esp8266
  Serial.println("YOUR_SSID");
  Serial.flush();
  Serial1.println("YOUR_SSID");
  Serial1.flush();
  delay(100);

  // send wifi password to esp8266
  Serial.println("YOUR_WIFI_PASSWORD");
  Serial.flush();
  Serial1.println("YOUR_WIFI_PASSWORD");
  Serial1.flush();

  // esp8266 connects to AP
  // requests IP from DHCP server
  // connect to MQTT broker
  // publishes to clients topic
  // subscribes to clients/cmd topic
  // subscribes to dev/nodemcu/rx topic
  delay(10000);
}

void loop() {

  // send value of x to MQTT broker topic dev/nodemcu/tx
  Serial.println(x);
  Serial.flush();
  Serial1.println(x);
  Serial1.flush();
  x++;
  delay(5000);
}
```

**Comment by jumpswitch** [comment]
Im closing this issue because others have reported working solutions.
